export const LIMITS = {
  MAX_TOTAL_BLOCKS: 2000,
  MAX_NESTED_DEPTH: 20,
  MAX_TEXT_NODE_LENGTH: 50000,
  MAX_BUTTON_TEXT_LENGTH: 200,
  MAX_URL_LENGTH: 2048,
  MAX_STATS_ITEMS: 20,
  MAX_SERIALIZED_PAYLOAD_SIZE_MB: 2,
} as const;
