export const DEFAULTS = {
  stat: {
    schemaVersion: 1,
    number: "10K+",
    label: "Active Users",
    backgroundColor: "#eff6ff",
    numberColor: "#1d4ed8",
    labelColor: "#6b7280",
    borderColor: "#bfdbfe",
    borderWidth: 2,
    radius: 16,
    shadow: "small",
    width: 320,
    height: 170,
    alignment: "center",
  },

  statsGroup: {
    schemaVersion: 1,
    stats: JSON.stringify([
      { number: "10K+", label: "Active Users" },
      { number: "99.9%", label: "Uptime" },
    ]),
    direction: "horizontal",
    alignment: "center",
    gap: 16,
    backgroundColor: "#eff6ff",
    numberColor: "#1d4ed8",
    labelColor: "#6b7280",
    borderColor: "#bfdbfe",
    borderWidth: 2,
    radius: 16,
    shadow: "small",
    width: 260,
    height: 150,
  },

  button: {
    schemaVersion: 1,
    text: "Click Here",
    url: "https://",
    alignment: "center",
    backgroundColor: "#2563eb",
    textColor: "#ffffff",
    hoverColor: "#1d4ed8",
    borderColor: "#2563eb",
    borderWidth: 0,
    radius: 8,
    shadow: "small",
    width: 180,
    height: 48,
    size: "medium",
    newTab: true,
  },
} as const;
