-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phoneVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "emailVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "authProvider" TEXT DEFAULT 'email',
ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3);
